[package]
name = "ssss"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm-siv = "0.11.1"
anyhow = "1.0.79"
aws-config = "1.1.2"
aws-sdk-kms = "1.10.0"
axum = { version = "0.7.3", default-features = false, features = ["json", "http1", "http2", "query", "tokio"] }
config = { version = "0.13.4", default-features = false, features = ["toml"] }
ethers = "2.0.11"
futures = { version = "0.3.30", default-features = false, features = ["std"] }
serde = { version = "1.0.195", features = ["derive"] }
thiserror = "1.0.56"
tokio = { version = "1.35.1", features = ["rt-multi-thread", "macros"] }
tower-http = { version = "0.5.0", features = ["trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }

[profile.release]
lto = "thin"
codegen-units = 1
