[profile.default]
optimizer = false
solc_version = "0.8.21"

remappings = [
  "@oasisprotocol/sapphire-contracts/contracts=lib/sapphire-paratime/contracts/contracts",
]

[rpc_endpoints]
emerald-testnet = "https://testnet.emerald.oasis.dev"
emerald-mainnet = "https://emerald.oasis.dev"
sapphire-testnet = "https://testnet.sapphire.oasis.dev"
sapphire-mainnet = "https://sapphire.oasis.io"

[fmt]
line_length = 100

[profile.release]
optimizer = true
optimizer_runs = 30_000
via_ir = true
