name: Build & Push escrin-runner Image

on:
  push:
    branches:
      - main

jobs:
  docker-build-and-push:
    strategy:
      matrix:
        env: [local, ne]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: worker/Dockerfile
          build-args: |
            WORKERD_TAG=v1.20231220.0
            DEPLOY_ENV=${{ matrix.env }}
          tags: |
            ghcr.io/escrin/runner:${{ github.sha }}-${{ matrix.env }}
            ghcr.io/escrin/runner:latest-${{ matrix.env }}
          push: true
          cache-from: type=registry,ref=ghcr.io/escrin/runner:latest-${{ matrix.env }}
          cache-to: type=inline

  eif-build-and-push:
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    container:
      image: amazonlinux:2023
    steps:
      - name: Install tools
        run: yum install aws-nitro-enclaves-cli aws-nitro-enclaves-cli-devel -y

      - name: Build EIF
        run: |
          set -o pipefail
          nitro-cli build-enclave --docker-uri ghcr.io/escrin/runner:latest-ne --output-file escrin-runner.eif \
          | tee escrin-runner.eif.json

      - name: Upload EIF
        uses: actions/upload-artifact@v3
        with:
          name: escrin-runner.eif
          path: escrin-runner.eif
          if-no-files-found: error

      - name: Upload measurements
        uses: actions/upload-artifact@v3
        with:
          name: escrin-runner.eif.json
          path: escrin-runner.eif.json
          if-no-files-found: error
